apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-tar-push-ui
  labels:
    app: docker-tar-push-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-tar-push-ui
  template:
    metadata:
      labels:
        app: docker-tar-push-ui
    spec:
      containers:
      - name: docker-tar-push-ui
        image: m.daocloud.io/404name/docker-tar-push-ui:latest
        ports:
        - containerPort: 8088  # 假设你的应用监听在 8080 端口
        env:
        - name: ROOT
          value: "."
        - name: TMP_DIR
          value: "tmp"
---
apiVersion: v1
kind: Service
metadata:
  name: docker-tar-push-ui-service
  labels:
    app: docker-tar-push-ui
spec:
  type: ClusterIP  # 或者 LoadBalancer 如果你需要外部访问
  ports:
  - port: 80
    targetPort: 8088
  selector:
    app: docker-tar-push-ui