apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-upload-portal
  labels:
    app: image-upload-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-upload-portal
  template:
    metadata:
      labels:
        app: image-upload-portal
    spec:
      containers:
      - name: image-upload-portal
        image: registry.cn-hangzhou.aliyuncs.com/404name/image-upload-portal:latest
        ports:
        - containerPort: 8088  # 假设你的应用监听在 8080 端口
        env:
        - name: ROOT
          value: "."
        - name: TMP_DIR
          value: "tmp"
---
apiVersion: v1
kind: Service
metadata:
  name: image-upload-portal-service
  labels:
    app: image-upload-portal
spec:
  type: ClusterIP  # 或者 LoadBalancer 如果你需要外部访问
  ports:
  - port: 80
    targetPort: 8088
  selector:
    app: image-upload-portal